server:
  port: 1112
eureka:
  instance:
    hostname: peer2
  client:
#    registerWithEureka: false
#    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${security.user.name}:${security.user.password}@peer1:1111/eureka/
#      defaultZone: http://peer1:1111/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 4000
security:
  user:
    name: testUser
    password: testPasswd
spring:
  application:
    name: eureka-server