server:
  port: 8080
management:
  port: 18081
  security:
    enabled: false
spring:
  jackson:
    serialization:
      indent-output: true
    deserialization: 
      fail-on-unknown-properties: false
logging:
  level:
    com.endofmaster: debug