server:
  port: 80
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/EndOfMaster/spring-cloud-demo/configrepo
          username: EndOfMaster
          password: ${GITHUB_PASSWORD}
