server:
  port: 1111
eureka:
  instance:
    hostname: peer1
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
#      defaultZone: http://${security.user.name}:${security.user.password}@peer2:1112/eureka/
      defaultZone: http://peer2:1112/eureka/