spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/EndOfMaster/spring-cloud-demo/configrepo
          username: EndOfMaster
          password: ${GITHUB_PASSWORD}
      username: test
      password: test
  profiles:
    active: prod
server:
  port: 8080