spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/EndOfMaster/configrepo
          username: 843698826@qq.com
          password: ${GITHUB_PASSWORD}
      username: test
      password: test
  profiles:
    active: prod
server:
  port: 8080