server:
  port: 8080
security:
  user:
    name: testUser
    password: testPasswd
spring:
  profiles:
    active: prod
  cloud:
    config:
      server:
        git:
          uri: https://github.com/EndOfMaster/configrepo
          username: 843698826@qq.com
          password: ${GITHUB_PASSWORD}
      username: test
      password: test
  application:
    name: config-server
eureka:
  client:
    service-url:
      defaultZone: http://${security.user.name}:${security.user.password}@${eureka.instance.ip-address}:1111/eureka/,${eureka.instance.ip-address}:1112/eureka/
#      defaultZone: http://127.0.0.1:8082/eureka/
  instance:
    lease-expiration-duration-in-seconds: 3
    lease-renewal-interval-in-seconds: 3
    ip-address: 127.0.0.1
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${eureka.instance.ip-address}:${server.port}